services:
  flask-site:
    build: .
    container_name: flask-site
    # restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Load from .env file
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - RCON_PASS=${RCON_PASS}
      - MC_HOST=${MC_HOST}
      - MC_PORT=${MC_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - REGISTRATION_ENABLED=${REGISTRATION_ENABLED}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PW=${MAIL_PW}
    volumes:
      # Mount uploads directory to persist user uploads
      - ./uploads:/app/uploads
      # Mount for development (comment out in production)
      # - .:/app
    networks:
      - flask-network
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        delay: 15s
    command: >
      sh -c "gunicorn --log-level debug --workers 2 --bind 0.0.0.0:8000 --timeout 120 --keep-alive 5 run:app"

  postgres:
    image: postgres:15
    container_name: flask-postgres
    # restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # Optional: set timezone
      TZ: America/New_York
    volumes:
      # Persistent data storage
      - postgres_data:/var/lib/postgresql/data
      # Initialization scripts - runs only on first startup
      - ./db-init:/docker-entrypoint-initdb.d
    # ports:
      # Expose for development/debugging (comment out in production)
      # - "5433:5432"
    networks:
      - flask-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  flask-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
