"""init migrate

Revision ID: 1350aca454f1
Revises: 
Create Date: 2025-09-30 22:22:25.940199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1350aca454f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('thumbnail',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='path to the thumbnail image, not the image itself',
               existing_nullable=True)
        batch_op.alter_column('last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='collection of post material: text, images'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_table_comment(
        'collection of post material: text, images',
        existing_comment=None
    )
        batch_op.alter_column('last_updated',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('thumbnail',
               existing_type=sa.TEXT(),
               comment='path to the thumbnail image, not the image itself',
               existing_nullable=True)

    # ### end Alembic commands ###
