"""Add is_draft field to BlogPost

Revision ID: ba76cbd4fd71
Revises: 1350aca454f1
Create Date: 2025-10-01 17:44:00.241749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba76cbd4fd71'
down_revision = '1350aca454f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        # Add column with server_default to set existing posts as published (False)
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
