"""Add MinecraftLocation model for fast travel (TC-46)

Revision ID: bf2b0947f570
Revises: ccb367647972
Create Date: 2025-11-21 21:36:36.037290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2b0947f570'
down_revision = 'ccb367647972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minecraft_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('position_z', sa.Float(), nullable=False),
    sa.Column('portrait', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Create indexes for better query performance
    op.create_index('ix_minecraft_locations_name', 'minecraft_locations', ['name'])
    op.create_index('ix_minecraft_locations_created_by_id', 'minecraft_locations', ['created_by_id'])
    op.create_index('ix_minecraft_locations_created_at', 'minecraft_locations', ['created_at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first
    op.drop_index('ix_minecraft_locations_created_at', table_name='minecraft_locations')
    op.drop_index('ix_minecraft_locations_created_by_id', table_name='minecraft_locations')
    op.drop_index('ix_minecraft_locations_name', table_name='minecraft_locations')

    op.drop_table('minecraft_locations')
    # ### end Alembic commands ###
