"""Add badge_color to Role model

Revision ID: ccb367647972
Revises: tc51_options_json
Create Date: 2025-10-19 00:51:44.847149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb367647972'
down_revision = 'tc51_options_json'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge_color', sa.String(length=7), nullable=False, server_default='#58cc02'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('badge_color')

    # ### end Alembic commands ###
